# Generated by Django 4.2.5 on 2025-01-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_email_remove_customer_name_and_more'),
        ('support', '0002_alter_servicerequest_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='customers.customer'),
        ),
    ]
