# Generated by Django 4.2.5 on 2025-01-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_date_submitted_servicerequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_csr',
            field=models.BooleanField(default=False),
        ),
    ]
